# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
plugins:
  - jekyll-seo-tag
# Site settings
title: Richard Gault
email: richard.gault22@gmail.com
description: Research Fellow in Computational Neuroscience
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://richardgault22.github.io" # the base hostname & protocol for your site
#twitter_username: hemang_kumar
github_username:  RichardGault22
google_scholar: Richard Gault
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
